### ISSUE TITLE
Thread already started

### ISSUE THREAD

**Issue by FortuneDream** [jackpocket/android_scratchoff#2]
By sample,I couldn't implement the effect that you have shown.
Throwing the Exception:   java.lang.IllegalThreadStateException: Thread already started
Android Studio did't tell me which line was error.

**Comment by mattsilber** [comment]
Can you show me the code you're using, please? As well as any data provided in the stack trace and what device model/os version you're running. That would help me figure out the issue, thanks~

**Comment by FortuneDream** [comment]
Genymotion->Samsung Galaxy S4 .API19
AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.q.scratchofftest, PID: 1303
                                                                            java.lang.IllegalThreadStateException: Thread already started
                                                                                at java.lang.Thread.checkNotStarted(Thread.java:871)
                                                                                at java.lang.Thread.start(Thread.java:1025)
                                                                                at com.jackpocket.scratchoff.processors.Processor.start(Processor.java:10)
                                                                                at com.jackpocket.scratchoff.processors.ThresholdProcessor.start(ThresholdProcessor.java:30)
                                                                                at com.jackpocket.scratchoff.processors.ScratchoffProcessor.start(ScratchoffProcessor.java:67)
                                                                                at com.jackpocket.scratchoff.ScratchoffController.onScratchableLayoutAvailable(ScratchoffController.java:105)
                                                                                at com.jackpocket.scratchoff.ScratchableLayoutDrawer.initializePostDisplay(ScratchableLayoutDrawer.java:99)
                                                                                at com.jackpocket.scratchoff.ScratchableLayoutDrawer.access$200(ScratchableLayoutDrawer.java:18)
                                                                                at com.jackpocket.scratchoff.ScratchableLayoutDrawer$2.run(ScratchableLayoutDrawer.java:81)
                                                                                at com.jackpocket.scratchoff.ViewHelper$1.onGlobalLayout(ViewHelper.java:22)
                                                                                at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:815)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1778)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by mattsilber** [comment]
I ensured that the processor would only be started if it was inactive, but I'm going to have to dive deeper to figure out how it got into a state where the processor starting was triggered twice in the first place. But 1.0.1 should at least prevent it from calling start() multiple times.

**Comment by szkodnik25** [comment]
Unfortunately, bug is still present. Just need to lock device and wake up again, when all desired lifecycle method are called - then crash occurs. Any ideas @mattsilber ?

**Comment by szkodnik25** [comment]
Yes, 1.1.0.
Indeed, that was my solution. Pretty decent, even though processing thread is running until fragment is destroyed. Definitely worth checking out.

**Comment by mattsilber** [comment]
So it looks like the Processor (which extends Thread) was actually being reused in the context of the Pausing -> Resuming.

I just launched a hotfix with version 1.2.0, dropped the Processor to an implementation of Runnable, which can then delegate the Thread creation appropriately. 

Also added a test repository (scratchoff-test) to easily play around with it, if you clone the repo.

Please let me know if this doesn't resolve your issues.
